



http://localhost:8000



###get all the task from api
GET http://localhost:8000/api/v1/task


###post all the response from api
POST http://localhost:8000/api/v1/task
Content-Type: application/json

{
    "task":"dancing",
    "hr": 13,
    "type":"entry"
    
}

### update taskt at api

PATCH  http://localhost:8000/api/v1/task
Content-Type: application/json

{
    "_id": "64850626e87317bc1b6d6df5",
    "type" :"entry"
}
### delete taskt at api

Delete http://localhost:8000/api/v1/task/64850626e87317bc1b6d6df5
Content-Type: application/json


